create extension if not exists pgcrypto;

create type public.user_role as enum ('admin', 'staff');
create type public.payout_status as enum ('Pending', 'Approved', 'Paid', 'Rejected');

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  role public.user_role not null default 'staff',
  created_at timestamptz not null default now()
);

create table if not exists public.kyc (
  id bigint generated by default as identity primary key,
  name text not null,
  status text not null check (status in ('Approved', 'Pending', 'Rejected')),
  updated_at timestamptz not null default now()
);

create table if not exists public.payouts (
  id bigint generated by default as identity primary key,
  merchant text not null,
  amount numeric(12, 2) not null check (amount > 0),
  status public.payout_status not null default 'Pending',
  paid_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer text not null,
  total numeric(12, 2) not null check (total >= 0),
  status text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  city text not null,
  orders integer not null default 0 check (orders >= 0),
  spend numeric(12, 2) not null default 0 check (spend >= 0)
);

alter table public.admin_users enable row level security;
alter table public.kyc enable row level security;
alter table public.payouts enable row level security;
alter table public.orders enable row level security;
alter table public.customers enable row level security;

create policy "authenticated users can read admin users"
  on public.admin_users for select to authenticated using (true);
create policy "authenticated users can read kyc"
  on public.kyc for select to authenticated using (true);
create policy "authenticated users can read payouts"
  on public.payouts for select to authenticated using (true);
create policy "authenticated users can insert payouts"
  on public.payouts for insert to authenticated with check (true);
create policy "authenticated users can approve payouts"
  on public.payouts for update to authenticated using (true) with check (true);
create policy "authenticated users can read orders"
  on public.orders for select to authenticated using (true);
create policy "authenticated users can read customers"
  on public.customers for select to authenticated using (true);

insert into public.admin_users (username, password_hash, role)
values
  ('admin', encode(digest('admin123', 'sha256'), 'hex'), 'admin'),
  ('staff', encode(digest('staff123', 'sha256'), 'hex'), 'staff')
on conflict (username) do nothing;

insert into public.payouts (merchant, amount, status)
values
  ('Fresh Laundry Co.', 3450.00, 'Paid'),
  ('Bubbles Wash', 1875.50, 'Pending'),
  ('Spark Clean', 2750.00, 'Approved')
on conflict do nothing;
